// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversidadApi.Data;

#nullable disable

namespace UniversidadApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UniversidadApi.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EscuelaId = 1,
                            Estado = "Operativa",
                            Nombre = "Ingeniería en Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            EscuelaId = 2,
                            Estado = "Operativa",
                            Nombre = "Ciencias Sociales"
                        },
                        new
                        {
                            Id = 3,
                            EscuelaId = 3,
                            Estado = "Operativa",
                            Nombre = "Medicina"
                        });
                });

            modelBuilder.Entity("UniversidadApi.Models.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Operativa",
                            Nombre = "Escuela de Ingeniería en Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Operativa",
                            Nombre = "Escuela de Ciencias Sociales"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Operativa",
                            Nombre = "Escuela de Medicina"
                        });
                });

            modelBuilder.Entity("UniversidadApi.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("UniversidadApi.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Curso introductorio a las matemáticas discretas",
                            EscuelaId = 1,
                            Estado = "Disponible",
                            Nombre = "Matemáticas Discretas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Fundamentos de física clásica",
                            EscuelaId = 1,
                            Estado = "Disponible",
                            Nombre = "Física General"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Curso que cubre técnicas avanzadas",
                            EscuelaId = 1,
                            Estado = "Disponible",
                            Nombre = "Programación Avanzada"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Estudio de la estructura del cuerpo humano",
                            EscuelaId = 3,
                            Estado = "Disponible",
                            Nombre = "Anatomía Humana"
                        });
                });

            modelBuilder.Entity("UniversidadApi.Models.MateriaCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("MateriaId");

                    b.ToTable("MateriasCarreras");
                });

            modelBuilder.Entity("UniversidadApi.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TpDescripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TpNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TpDescripcion = "Usuario con privilegios completos",
                            TpNombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            TpDescripcion = "Usuario con permisos para gestionar materias",
                            TpNombre = "Docente"
                        });
                });

            modelBuilder.Entity("UniversidadApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Gonzalez",
                            Correo = "eduar2.gm2020@gmail.com",
                            EscuelaId = 1,
                            Estado = "Activo",
                            FechaNac = new DateTime(2000, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Eduardo",
                            Password = "eduardo",
                            TipoUsuarioId = 1,
                            Username = "eduardo"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gonzalez",
                            Correo = "sngm@gmail.com",
                            EscuelaId = 3,
                            Estado = "Activo",
                            FechaNac = new DateTime(2006, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofia",
                            Password = "sofia",
                            TipoUsuarioId = 2,
                            Username = "sofia"
                        });
                });

            modelBuilder.Entity("UniversidadApi.Models.Carrera", b =>
                {
                    b.HasOne("UniversidadApi.Models.Escuela", "Escuela")
                        .WithMany()
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("UniversidadApi.Models.Grupo", b =>
                {
                    b.HasOne("UniversidadApi.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("UniversidadApi.Models.Materia", b =>
                {
                    b.HasOne("UniversidadApi.Models.Escuela", "Escuela")
                        .WithMany()
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("UniversidadApi.Models.MateriaCarrera", b =>
                {
                    b.HasOne("UniversidadApi.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadApi.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("UniversidadApi.Models.Usuario", b =>
                {
                    b.HasOne("UniversidadApi.Models.Escuela", "Escuela")
                        .WithMany()
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadApi.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuela");

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
